### ISSUE TITLE
Unable to load Disqus

### ISSUE THREAD

**Issue by zunction** [iKevinY/pneumatic#2]
Hi Kevin,

Thanks for this wonderful template that is what I have been looking for. Recently I decided that I wanted to implement Disqus for my blog but using `make devserver` following by viewing it on my localhost, i get the message 'We were unable to load Disqus. If you are a moderator please see our troubleshooting guide.' . Could I get some help on you to see why this is happening? I'm not good with html and stuff; hence I don't dare to play around with your template to try to fix it.

Thanks!

**Comment by iKevinY** [comment]
Hi @zunction! I disabled Disqus on my website a while ago, so thanks for bringing this to my attention! It looks like they've altered their "[universal install code](https://disqus.com/admin/universalcode/)", so I'll make those same changes.

**Comment by iKevinY** [comment]
Alright, I think 1ce05819101a4923b78fcbc3baeab54c224dd397 fixes this issue. As long as you've set your  `SITEURL` and `DISQUS_SITENAME` properly, the comments should load properly. The only caveat is that if you have `RELATIVE_URLS` set to `True` (like I do when I test my site locally), the comments won't load, because `SITEURL` becomes relative (ie. `../../..`), and Disqus' embed script doesn't like this.

**Comment by zunction** [comment]
Thanks @iKevinY ! It is working well now! Happy New Year !

**Comment by iKevinY** [comment]
Good to hear! Happy New Year to you too!
