### ISSUE TITLE
Font not being applied

### ISSUE THREAD

**Issue by amitness** [iKevinY/pneumatic#4]
I used your theme for my blog: https://amitness.com/ . But the fonts is not like how it's in the screenshot and demo page. 

I referred your blog setup and also added the font names to pelicanconf.py. 

https://github.com/amitness/amitness.github.io

**Comment by iKevinY** [comment]
The version of Pneumatic that I use with my website is slightly different from `master`. The demo screenshot was captured using Raleway, rather than Nunito Sans. You'll want to either modify [`pneumatic.scss`](https://github.com/iKevinY/pneumatic/blob/iKevinY.github.io/static/pneumatic.scss) to use Nunito Sans as the main font, or use Raleway in your configuration:

```python
GOOGLE_FONTS = [
    "Raleway:400,600",
    "Source Code Pro",
]
```

**Comment by amitness** [comment]
I liked the Nunito Sans font and updating the pneumatic.scss file fixed the issue. Thanks a lot for the awesome theme.
